---
- name: loop
  hosts: all
  become: true
  become_method: sudo
  connection: ssh
  ignore_errors: false
  tasks:
    - name: loop
      package: 
        name: "{{item}}"
        state: present
      with_items:
        - httpd
        - telnet
        - lftp
        - unzip
        - wget

    - name: command 
      command: "{{item}}"
      with_items:
        - "yum install telnet"
        - "free -m"
        - "w"